-- Create database (edit name if needed)
CREATE DATABASE IF NOT EXISTS file_portal CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE file_portal;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  phone VARCHAR(20),
  password VARCHAR(255) NOT NULL,
  is_admin TINYINT(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS files (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT DEFAULT NULL,
  filename_orig VARCHAR(255) NOT NULL,
  filename_disk VARCHAR(255) NOT NULL,
  folder_type ENUM('public','private') NOT NULL,
  folder_path VARCHAR(255) NOT NULL,
  size INT NOT NULL,
  mime VARCHAR(100),
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
